<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "lvaddress"
 *
 * Auto generated by Extension Builder 2016-06-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Adressen',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Lars Vogel',
    'author_email' => 'info@l-vogel.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '',
    'constraints' => [
        'depends' => [
            'extbase' => '7.6',
            'fluid' => '7.6',
            'typo3' => '7.6'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
