<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "lvaddress"
 *
 * Auto generated by Extension Builder 2016-08-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Adressen',
    'description' => '',
    'category' => 'plugin',
    'author' => '',
    'author_email' => '',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '',
    'constraints' => [
        'depends' => [
            'extbase' => '6.2',
            'fluid' => '6.2',
            'typo3' => '6.2',
            'static_info_tables' => '6.0',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
